import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Cookies from 'js-cookie'
import { ABOUT_BUCKETS } from 'lib/buckets'
import {
  DeployButton,
  DocButton,
  ExamplesButton,
  LearnButton,
} from 'components/buttons'
import styles from 'styles/Home.module.css'
import type { NextPage } from 'next'

const AboutVariant: NextPage = () => {
  const router = useRouter()

  const setBucket = (bucket: string) => () => {
    Cookies.set('bucket-about', bucket)
    router.reload()
  }
  const removeBucket = () => {
    Cookies.remove('bucket-about')
    router.reload()
  }

  const currentBucket = router?.query?.bucket as string

  return (
    <div className={styles.container}>
      <Head>
        <title>About Next.js [Variant]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          About Next.js [{currentBucket.toUpperCase()}]
        </h1>
        <h3>You&apos;re currently in Bucket {currentBucket.toUpperCase()}</h3>

        <div className={styles.buttons}>
          {ABOUT_BUCKETS.map((bucket) => (
            <button key={bucket} onClick={setBucket(bucket)}>
              {bucket}
            </button>
          ))}
          <button onClick={removeBucket}>remove bucket</button>
        </div>

        <p className={styles.description}>
          <Link href="/">← back home</Link>
        </p>

        <div className={styles.grid}>
          {currentBucket === 'new-cta' ? (
            <>
              <DeployButton />
              <ExamplesButton />
              <DocButton />
              <LearnButton />
            </>
          ) : (
            <>
              <DocButton />
              <LearnButton />
              <ExamplesButton />
              <DeployButton />
            </>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticPaths() {
  const buckets = ABOUT_BUCKETS.filter((bucket) => bucket !== 'original')
  const paths = buckets.map((bucket) => ({ params: { bucket } }))

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps() {
  // Here you would return data about the bucket
  return { props: {} }
}

export default AboutVariant
