import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Cookies from 'js-cookie'
import { ABOUT_BUCKETS } from 'lib/buckets'
import {
  DeployButton,
  DocButton,
  ExamplesButton,
  LearnButton,
} from 'components/buttons'
import styles from 'styles/Home.module.css'
import type { NextPage } from 'next'

const About: NextPage = () => {
  const router = useRouter()

  const setBucket = (bucket: string) => () => {
    Cookies.set('bucket-about', bucket)
    router.reload()
  }

  const removeBucket = () => {
    Cookies.remove('bucket-about')
    router.reload()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>About Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About Next.js</h1>

        <h3>You are not currently in a bucket</h3>

        <div className={styles.buttons}>
          {ABOUT_BUCKETS.map((bucket) => (
            <button key={bucket} onClick={setBucket(bucket)}>
              {bucket}
            </button>
          ))}
        </div>

        <p className={styles.description}>
          <Link href="/">← back home</Link>
        </p>

        <div className={styles.grid}>
          <DocButton />
          <LearnButton />
          <ExamplesButton />
          <DeployButton />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default About
